# Generated by Django 4.2.4 on 2024-05-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_ic', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('employee_name', models.TextField(max_length=255)),
                ('employee_email', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=50)),
                ('num_phone', models.CharField(max_length=12)),
                ('position', models.TextField(max_length=255)),
                ('department', models.TextField(max_length=255)),
                ('salary', models.CharField(max_length=7)),
                ('emergency_num', models.CharField(max_length=12)),
                ('emergency_name', models.TextField(max_length=255)),
                ('emp_username', models.CharField(max_length=255)),
                ('emp_password', models.CharField(max_length=255)),
            ],
        ),
    ]
