# Generated by Django 4.2.4 on 2024-06-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeleavesystem', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(max_length=255)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(max_length=255)),
                ('employee_ic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeleavesystem.employee')),
            ],
        ),
    ]
