# Generated by Django 4.2.4 on 2024-06-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeleavesystem', '0005_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=255)),
                ('announcement_content', models.CharField(max_length=255)),
                ('announcement_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
