# Generated by Django 4.2.4 on 2024-06-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeleavesystem', '0006_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=7)),
                ('total_date', models.CharField(max_length=2)),
                ('package_detail', models.CharField(max_length=255)),
                ('hotel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('available', models.CharField(default='Available', max_length=10)),
                ('employee_ic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeleavesystem.employee')),
            ],
        ),
    ]
