# Generated by Django 4.2.4 on 2024-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeleavesystem', '0008_employee_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
