# Generated by Django 4.2.4 on 2024-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeleavesystem', '0009_employee_total_leave_leave_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_pic.png', null=True, upload_to='profile_pics/'),
        ),
    ]
